name: .venv
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python=3.9.16
  - ipykernel=6.28.0
  - category_encoders>=2.4.0
  - feature_engine>=1.4.0
  - featuretools>=1.5.0
  - matplotlib>=3.4.2
  - matplotlib-inline>=0.1.2
  - numpy>=1.22.2
  - pandas>=1.5.0
  - scikit-learn>=1.1.0
  - scipy>=1.7.0
  - seaborn>=0.11.1
  - statsmodels>=0.12.2